---
# 更新快取
- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install tools
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker apt key (alternative for older systems without SNI 1).
  shell: "curl -fsSL {{apt_key_url}} | sudo gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg"

- name: Add Docker apt key (alternative for older systems without SNI 2).
  shell: >
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

