---
# 更新快取
- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install docker-ce
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io