---
- include_tasks: removeDocker.yml
- include_tasks: addGpg.yml
- include_tasks: installDocker.yml
- include_tasks: docker-users.yml
- include_tasks: installDockerCompose.yml

- name: Create {{ docker_home }} directory
  file:
    path: "{{ docker_home }}"
    state: directory

# - name: Reboot at now
#   command: /sbin/shutdown -r now